### ISSUE TITLE
Criação de Bot para Extração de Diários Oficiais

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#12]
## Objetivo:
Criar um bot que automatize a extração dos Diários Oficiais do http://www.diariomunicipal.com.br/ama, converta os PDFs em arquivos de texto (TXT) e organize os dados separadamente para cada município.

## Tarefas:
**Extração dos Diários Oficiais**
- [x]  Desenvolver um script de web scraping para acessar o site http://www.diariomunicipal.com.br/ama e coletar os PDFs dos Diários Oficiais.

**Banco de dados**
- [x] Definir como e onde serão armazenados os Diários Oficiais @joycedio

**Documentação**
- [x] Fazer o commit do bot;
- [x] Documentação de como usar o bot.

**Comment by joycedio** [comment]
O banco de dados que será usado é o PostgreSQL, a primeira documentação da estruturação está na [wiki](https://github.com/unb-mds/2023-2-Squad03/wiki/Defini%C3%A7%C3%A3o-do-Banco-de-Dados).

**Comment by M4RINH0** [comment]
Bot Feito em Python usando Selenium e Pydrive
