### ISSUE TITLE
Definição de Personas do Projeto

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#13]
## Objetivo
Identificar e documentar as personas que serão o foco do projeto e ajudarão a orientar o desenvolvimento e garantir que as soluções atendam às necessidades dos usuários finais.

**Pesquisa de Usuários**
- [x] Realizar pesquisa de usuários para coletar informações sobre os potenciais usuários do projeto.
- [x]  Identificar características demográficas, necessidades, dores e objetivos dos usuários.

**Definição de Personas**
- [x] Com base na pesquisa de usuários, criar personas detalhadas que representem grupos de usuários-chaves
- [x] Cada persona deve incluir cargo, necessidades principais, objetivos, etc.

Validação das Personas:
- [x]  Compartilhar as personas com a equipe do projeto obter feedback e validação

Documentação:
- [x] Criar documentação com todas as personas definidas.

**Comment by DiegoSousaLeite** [comment]
Foi feita a documentação do significado de uma persona, junto com 3 exemplos de personas para o trabalho
