### ISSUE TITLE
Definição dos Stakeholders do Projeto

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#14]
## Objetivo
Identificar e documentar os stakeholders-chave do projeto após a definição das personas.

## Tarefas

**Revisão das Personas**
- [x] Rever as personas definidas anteriormente para identificar grupos de usuários e partes interessadas que podem ser considerados stakeholders.

**Identificação de Stakeholders**
- [x] Listar os stakeholders identificados, incluindo suas informações de contato e suas áreas de interesse ou influência no projeto.

**Priorização dos Stakeholders**
- [x]  Priorizar os stakeholders com base em seu impacto e influência no projeto.

**Comunicação**
- [x] Desenvolver um plano de comunicação e engajamento dos stakeholders, descrevendo como a equipe do projeto irá interagir com eles e manter uma comunicação eficaz.

**Documentação**
Criar documentação que contenha todos os dados dos stakeholders definidos.

## Observação
Analisar issue #13

**Comment by Paxxaglia** [comment]
Efetuei a Documentação dos Stakeholders com base nas personas como também o plano de comunicação que será aplicado para feedback sobre atualizações no projeto.
