### ISSUE TITLE
 Início do Levantamento de Requisitos do Projeto

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#15]
## Objetivos
Iniciar o processo de levantamento de requisitos do projeto após a identificação dos stakeholders.

## Tarefas
**Coleta de Informações**
- [x]  Entrar em contato com os stakeholders para iniciar as conversas sobre suas necessidades e requisitos específicos.
- [x]  Preparar uma lista de perguntas e tópicos a serem abordados durante as entrevistas ou reuniões com os stakeholders.

**Reuniões com Stakeholders**
- [x] Realizar entrevistas individuais ou reuniões com os stakeholders para coletar informações sobre suas necessidades, expectativas e requisitos.
- [x]  Registrar as respostas e insights obtidos durante as conversas.

**Documentação de Requisitos**
- [x] Documentar no figma os requisitos iniciais com base nas informações coletadas das entrevistas e reuniões.

## Observações
Analisar as issues #14 e #13

**Comment by brunocva** [comment]
Definimos os requisitos, está no [link](https://github.com/unb-mds/2023-2-Squad03/wiki/Requisitos-n%C3%A3o-funcionais-e-funcionais).
