### ISSUE TITLE
Conversão dos Diários Oficiais de PDF para TXT

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#17]
## Objetivo:
Após a extração dos Diários Oficiais, fazer a conversão de PDF para TXT e fazer a segmentação por municipio.

## Tarefas
**Organização dos Dados por Município**
- [x] Desenvolver um algoritmo que analise o conteúdo dos TXTs e separe os dados específicos de cada município.
- [x] Criar arquivos TXT individuais para cada município com os dados de cada municipio.

**Comment by MarcoTulioSoares** [comment]
Criei o código que a partir de uma lista de municípios consegue filtrar cada licitação de acordo com a sua localidade
