### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#18]
## Objetivos
Desenvolver protótipo de baixa fidelidade que representem visualmente as principais funcionalidades e fluxos do sistema com base nos requisitos levantados

## Tarefas
**Revisão de Requisitos**
- [x] Revisar os requisitos levantados para obter uma compreensão completa das funcionalidades e fluxos necessários.

**Definição de Escopo dos Protótipos**
- [x] Identificar as principais funcionalidades e fluxos que serão representados nos protótipos de baixa fidelidade.
- [x]  Estabelecer quais áreas do sistema serão priorizadas.

**Criação dos Protótipos**
- [x]  Desenvolver no figma esboços simples que representem as telas e interações do sistema.

**Documentação**
- [x] Documentar a funcionalidade do protótipo inicial.

**Comment by Paxxaglia** [comment]
Foi feito o protótipo de baixa fidelidade no figma conforme descrito na documentação (WIKI)

[https://www.figma.com/file/96uxk3VlJ6gF5c6VmKPyeq/Little-Insights%3A-Simplified-Analytics-Dashboard-(Community)?type=design&node-id=0%3A1&mode=design&t=DUPqOKC83okQaI5N-1](url)

**Comment by Paxxaglia** [comment]
Foi feito o protótipo de baixa fidelidade no figma conforme descrito na documentação (WIKI)

[https://www.figma.com/file/96uxk3VlJ6gF5c6VmKPyeq/Little-Insights%3A-Simplified-Analytics-Dashboard-(Community)?type=design&node-id=0%3A1&mode=design&t=DUPqOKC83okQaI5N-1](url)
