### ISSUE TITLE
Vincular banco de dados com o bot

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#21]

**Comment by joycedio** [comment]
Eu fiz um notebook que manipula os dados que estão nos arquivos txt de cada municipio, e insiro esses dados em um banco de dados de exemplo criado no PostgreSQL.

O notebook está no [repositório](https://github.com/unb-mds/2023-2-Squad03/blob/main/BOTS/database.ipynb)
