### ISSUE TITLE
Vincular Bot com o Conversor

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#22]
**Descrição:**
O objetivo deste issue é implementar a integração do bot com um conversor de PDF para TXT. Isso permitirá que o bot seja capaz de converter documentos em formato PDF em texto simples (TXT), facilitando a extração de informações de documentos PDF em conversas.

**Tarefas:**
- [x] Configurar as dependências necessárias no ambiente de desenvolvimento do bot.
- [x] Implementar um comando ou função no bot para receber e processar documentos PDF.
- [x] Integrar o conversor de PDF escolhido ao bot para converter os PDFs recebidos em texto.
- [x] Lidar com casos de erro ou exceções que possam ocorrer durante a conversão.
- [x] Documentar o processo de integração para referência futura.

**Critérios de Aceitação:**
- [x] O bot é capaz de receber documentos PDF de usuários.
- [x] A funcionalidade de conversão de PDF para TXT é testada e considerada estável.
- [x] O bot lida adequadamente com erros ou problemas que possam surgir durante a conversão.
- [x] O processo de integração é documentado de forma clara e organizada.

**Comment by M4RINH0** [comment]
Feito em Call Com o @omascara2 a união do bot e conversor
