### ISSUE TITLE
Estudar API Flesk 

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#23]
**Descrição:**
A pessoa responsável por este issue está iniciando um processo de aprendizado para dominar a arte da criação de APIs com o framework Flesk. Este issue serve como um registro de progresso, definição de metas de estudo e um canal para colaborar com a comunidade em busca de orientações e recursos úteis.

**Tarefas:**
- [x] Pesquisar e revisar a documentação oficial do Flesk sobre criação de APIs.
  - [x] Configurar um ambiente de desenvolvimento Flesk.
- [x] Criar um projeto Flesk de teste para começar a construir uma API simples.
- [x] Estudar os conceitos de serialização de dados e criação de modelos de API.
- [x] Explorar autenticação e autorização em APIs Flesk.
- [x] Testar a API utilizando ferramentas como o Postman ou o Insomnia.

**Critérios de Sucesso:**
- [x] Documentar o processo de criação da API, incluindo passos e desafios encontrados.
- [x] Ser capaz de criar uma API funcional que possa ser usada para interagir com um aplicativo front-end ou outros sistemas.

**Comment by PedroHenrique061** [comment]
Pesquisei e estudei sobre o framework Flask(python), preparei o ambiente de desenvolvimento para a criação das APIs.
Por fim, realizei alguns testes usando o Postman.

**Comment by brunocva** [comment]
Ao pesquisarmos a ferramenta a ser usada, optamos pelo framework flask, para a criação das APIs.
