### ISSUE TITLE
Criação da página Home e Sobre

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#28]
**Descrição Geral:**
Nossa aplicação precisa de uma página "Home" para dar as boas-vindas aos visitantes e uma página "Sobre" para fornecer informações sobre o projeto. Esta issue é para rastrear o desenvolvimento dessas duas páginas.

**Tarefas:**

1. **Criação da Página "Home"**
   - [x] Criar a estrutura básica da página "Home".
   - [x] Estilizar a página "Home" para garantir uma experiência de usuário atraente.

2. **Criação da Página "Sobre"**
   - [x] Criar a estrutura básica da página "Sobre".
   - [x] Adicionar informações sobre o projeto, sua equipe e sua missão.
   - [x] Estilizar a página "Sobre" para que seja informativa e visualmente agradável.

**Critérios de Aceitação:**
- As páginas "Home" e "Sobre" devem estar acessíveis a partir do menu de navegação.
- As páginas devem ser criadas de acordo com as diretrizes de design do projeto.

**Comment by Paxxaglia** [comment]
Foi criado a pagina Home e sobre conforme pode ser visto no respectivo repositório.
