### ISSUE TITLE
Implementação do Scrum para Gerenciamento de Projeto

### ISSUE THREAD

**Issue by M4RINH0** [unb-mds/2023-2-Squad03-LicitAL#3]
# Descrição
Rastrear o processo de implementação do Scrum e discutir os passos necessários para a sua adoção.

# Tarefas

- [x] Pesquisar e identificar as melhores práticas de implementação do Scrum.
- [x] Desenvolver um plano de treinamento para a equipe
- [x] Designar papéis e responsabilidades dentro da equipe Scrum (Scrum Master, Product Owner, Membros do Time).
- [x] Documentar o processo de implementação do Scrum.

# Critérios de aceitação 

- [x] O plano de implementação do Scrum é criado e documentado.
- [x] A equipe participa de treinamentos para compreender os princípios do Scrum.

# Observação
- [Definição da equipe](https://docs.google.com/spreadsheets/d/15OQeK5pMGepuDb3DUOzgqvI3MF_nNi_rx_TuUlDD3Ag/edit?usp=sharing)

**Comment by joycedio** [comment]
@Sooties @M4RINH0 @Paxxaglia @omascara2 @PedroHenrique061 @brunocva 
A documentação sobre o que é Scrum ta [aqui](https://github.com/unb-mds/2023-2-Squad03/wiki/Scrum)

Depois só preencher essa [planilha](https://docs.google.com/spreadsheets/d/15OQeK5pMGepuDb3DUOzgqvI3MF_nNi_rx_TuUlDD3Ag/edit?usp=sharing) pra documentar os papéis dentro da Scrum
