### ISSUE TITLE
Ultimas preparações para entrega da R1

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#35]
**Descrição**

Nossa equipe está se aproximando da data de entrega da Release 1 (R1) e é crucial garantir que todas as tarefas estejam concluídas e todos os problemas resolvidos antes do prazo. Esta issue é criada para rastrear todas as atividades necessárias para finalizar a R1 com sucesso.

**Tarefas Pendentes:**

- [x] Revisar e confirmar a lista de recursos e correções planejados para a R1.

    - [x] 1.README de documentação pronta (até o necessário para primeira entrega)
    - [x] 2.README de front precisa de um passo a passo de como rodar aplicação (melhorar o atual)
    - [x] 3.Renomear os arquivos do front (tem algumas hashs esquisitas nos nomes atuais) 
    - [x] 4.Detalhar na documentação como vocês estão seguindo as metodologias ágeis
    - [x] 5.Cada membro tem que fechar uma issue relevante
    - [x] 6.Dica pessoal - fazer uma gitpage para documentação
    - [x] 7.Melhorar a documentação (deixar tudo rastreável)
    - [x] 8.Story Map
    - [x] 9.Doc de arquitetura 

- [x] Revisar e atualizar a documentação do usuário, se necessário.
- [x] Preparar a versão final da R1 para entrega.

**Comment by joycedio** [comment]
Concluimos as adaptações que os monitores indicaram onde era preciso melhorar
