### ISSUE TITLE
estudar metodologia xp

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#42]

**Comment by M4RINH0** [comment]
uma metodologia focada em erros e acertos com base na programação com uso de testes e atividades de desenvolvimento em grupo

**Comment by MarcoTulioSoares** [comment]
A Metodologia XP é uma abordagem ágil de desenvolvimento de software que enfatiza a comunicação constante, feedback rápido e o trabalho em equipe
