### ISSUE TITLE
template issue

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#45]
### Descrição
Criar um template de issue padronizado para facilitar a documentação e acompanhamento de tarefas no projeto.

### Tarefas

1. **Estrutura Básica**
   - [ ] Criar uma estrutura básica para todas as issues, incluindo seções como Descrição, Tarefas, Critérios de Aceitação,Prazo e Responsáveis.

2. **Detalhes Padrão**
   - [ ] Incluir detalhes padrão em cada seção para guiar os colaboradores na criação consistente de issues.

### Critérios de Aceitação
- [ ] O template de issue está completo e pronto para uso.
- [ ] Cada seção do template possui instruções claras e úteis.
- [ ] O template é facilmente compreensível para novos membros da equipe.

**Comment by DiegoSousaLeite** [comment]
Foi feito o template para as issues

**Comment by DiegoSousaLeite** [comment]
## Esse é o template

### Descrição
[Breve descrição do que a issue se propõe a fazer.]

### Tarefas

1. *[Tarefa 1]*
   - [ ] [Detalhe específico da tarefa 1]
   - [ ] [Outro detalhe, se aplicável]

2. *[Tarefa 2]*
   - [ ] [Detalhe específico da tarefa 2]
   - [ ] [Outro detalhe, se aplicável]

3. *[Tarefa 3]*
   - [ ] [Detalhe específico da tarefa 3]
   - [ ] [Outro detalhe, se aplicável]

### Critérios de Aceitação
- [ ] A [funcionalidade/tarefa] está implementada de acordo com os requisitos.
- [ ] [Outro critério específico de aceitação]
- [ ] [Mais um critério, se aplicável]
