### ISSUE TITLE
Atualizar logos do front

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#46]
### Descrição
Atualizar os logos no frontend para garantir consistência e uma imagem atualizada no projeto.

### Tarefas

1. **Verificação dos Logos Atuais**
   - [x] Verificar os logos atuais em uso no frontend.

2. **Seleção de Novos Logos**
   - [x] Selecionar novos logos que atendam aos requisitos de design e identidade visual do projeto.

### Critérios de Aceitação
- [x] Os novos logos estão implementados no frontend.
- [x] Os logos são visualmente consistentes com a identidade visual do projeto.
- [x] Os logos estão exibindo corretamente em diferentes dispositivos e tamanhos de tela.

**Comment by Paxxaglia** [comment]
As logos necessárias foram devidamente expostos onde se fazia necessário.
