### ISSUE TITLE
Atualização de Integrantes do Grupo - Frontend

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#47]
### Descrição
Atualizar a lista de integrantes do grupo no frontend para refletir com precisão a composição atual da equipe. Isso é essencial para manter a transparência e a comunicação eficaz dentro do projeto.

### Tarefas

1. **Atualização da Página de Equipe**
   - [ ] Atualizar a página de equipe no frontend com os nomes e informações mais recentes dos membros.

2. **Informações Adicionais**
   - [ ] Verificar se há informações adicionais (por exemplo, cargos, responsabilidades) que precisam ser atualizadas.

### Critérios de Aceitação
- [ ] A página de equipe no frontend reflete com precisão a lista atualizada de membros.
- [ ] Qualquer informação adicional é revisada e atualizada conforme necessário.

**Comment by Paxxaglia** [comment]
Foram atualizados os nomes dos integrantes do grupo no Front-end do projeto LicitAL
