### ISSUE TITLE
Separar cidades por arquivo

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#49]
### Descrição
Aprimorar a estrutura de dados das cidades, separando cada cidade em um arquivo individual para melhor organização e manutenção.

### Tarefas

1. **Criar Arquivos Individuais**
   - [x] Criar um arquivo separado para cada cidade no diretório apropriado.

2. **Mover Dados Existente**
   - [x] Transferir os dados das cidades para seus respectivos arquivos.

3. **Atualizar Lógica de Leitura**
   - [x] Modificar a lógica de leitura para considerar os arquivos individuais.
   - [x] Garantir que o sistema funcione corretamente após a separação.

### Critérios de Aceitação
- [x] Cada cidade possui seu próprio arquivo de dados.
- [x] Todos os dados foram transferidos com precisão para os arquivos correspondentes.
- [x] O sistema continua a funcionar corretamente após a implementação.

**Comment by M4RINH0** [comment]
Usando como base o arquivo principal que recebe os dados de todas as cidades, gerei um arquivo para cada cidade com o formato desejado usando a biblioteca json do python agora deve fazer os testes ao mandar os requerimentos para o site.(Arquivos Presentes na pasta /site)
