### ISSUE TITLE
Organizar os dados dentro dos arquivos

### ISSUE THREAD

**Issue by joycedio** [unb-mds/2023-2-Squad03-LicitAL#50]
### Descrição
Esta issue tem como objetivo organizar os dados presentes nos arquivos do projeto para melhorar a legibilidade e manutenibilidade do código.

### Tarefas

1. **Reestruturação dos Arquivos**
   - [x] Organizar os dados nos arquivos para seguir um padrão consistente.

2. **Verificação da Consistência**
   - [x] Garantir que a organização dos dados seja igual a do Exoonero.

### Critérios de Aceitação
- [x] Os dados nos arquivos estão organizados de acordo com o novo padrão estabelecido.

**Comment by DiegoSousaLeite** [comment]
Dados organizados falando o geral
