### ISSUE TITLE
Corrigir bugs do Frontend - URGENTE

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#64]
### Descrição
Esta issue tem como objetivo corrigir bugs específicos relacionados à GitHub Pages, que estão afetando a correta exibição da aplicação no ambiente de produção.

### Tarefas

1. **Erro na Renderização da GitHub Pages**
   - [ ] Investigar e corrigir problemas na renderização da aplicação na GitHub Pages.
   - [ ] Certificar-se de que todos os recursos e estilos estão sendo carregados corretamente.

### Critérios de Aceitação
- [ ] A aplicação é renderizada corretamente na GitHub Pages, sem erros visuais.

**Comment by Paxxaglia** [comment]
Foram corrigidos os bugs com relação  ao gitpages (o gitpages só gera servidores estaticos), portanto, deploy foi alterado para o vercel
