### ISSUE TITLE
Atualizar gráficos do front

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#65]
### Descrição
Atualizar os gráficos na interface do usuário para melhorar a experiência do usuário e fornecer informações adicionais.

### Tarefas
1. **Melhorar a apresentação visual**
   - [x] Ajustar estilos e cores para uma apresentação visual mais atraente.
   - [x] Garantir consistência na aparência dos diferentes tipos de gráficos.

### Critérios de Aceitação
- [x] A apresentação visual dos gráficos foi aprimorada de acordo com as diretrizes de design.

**Comment by Paxxaglia** [comment]
Corrigida a forma como eram mostrados os dados nos graficos. tinhamos um leve problema com as escalas que foi solucionado
