### ISSUE TITLE
Estudar para Ciência de Dados

### ISSUE THREAD

**Issue by DiegoSousaLeite** [unb-mds/2023-2-Squad03-LicitAL#8]
# Descrição 
Estudar python para ciencia de dados. Apreender a utilizar as principais bibliotecas de
manipulação de banco de dados

# Tarefa
- [x] Identificar bibliotecas de ciencias dados

- [x] Fazer um exemplo de código usando pandas e numpy

- [x] Implementar um raspador com regex para extrair CPF e nomes do Diário oficial

- [x] Implementar usando Jupyter notebook

# Criterios de acitação

- [x] Notebooks commitados no repositorio

- [x] Documentação de configuração de ambiente

- [x] Treinameto com a equipe

**Comment by MarcoTulioSoares** [comment]
Fiz o raspador e uma wiki explicando a biblioteca
